### ISSUE TITLE
NPE errors on player joins, causing joining to fail.

### ISSUE THREAD

**Issue by Absentee23** [Cube-Space/geSuit#37]
Errors seen here:
http://pastebin.com/1jtTpdsP

This was while a few people were joining, and during this period connecting would either take a long time, or fail entirely and disconnect them.

**Comment by geNAZt** [comment]
This was fixed 11 days ago

**Comment by Absentee23** [comment]
I'm running the latest geSuit and associated bukkit modules (except bans), though I'll go ahead and redownload the latest off jenkins to be sure (possibly missed one in an update?)

Was it a fix in Yamler? I'm still on 1.5.2 snapshot because it seems to throw an error and fail to start gesuit with anything newer, and I assumed Yamler was just for the config files.

**Comment by Absentee23** [comment]
**edited** with new info

This most certainly isn't fixed. Spigot (build ~~1422~~ 1427), BungeeCord (build ~~892~~ 897) (~~haven't had a chance to update to todays builds~~ got a chance to update, had another occurence after). Latest geSuit off of jenkins (build 66), latest CloudChat (build 130), latest BungeeLib (build 3, cubespace-bungeelib.jar), and still Yamler 1.5.2.

Today: http://pastebin.com/KuFU3s1s NOTE: from the original pastebin in this thread, the geSuitspawns error is NOT there. I think you saw that and assumed that was the only problem? I haven't seen that since pulling all newest jenkins builds (like I said, I must have missed grabbing spawns.jar or something).

However this error persists, and _sometimes_ immediately after it occurs, CloudChat joining global chat upon login breaks. **Edit: it seems breaking cloudchat might be coincidental, or only intermittent: had another occurrence of this error after updating spigot/bungee tonight without it breaking global chat joining.** Only kicked the player with "you logged in from another location" in the spigot console (obviously spigot behind bungee is offline, but the proxy is in online mode). This time it also happened on off-hours with only a single person (re)joining, and the instances where it breaks cloudchat are always during peak-hours with multiple joins close together.

 Its very hard to get a report, because it happens so suddenly and randomly. MAY be caused by the recent 1.7.8 protocol changes, at it seemed to crop up around the same time, but I'm just speculating.
